# -*- coding: utf-8 -*-
"""ComfyUI 工作流定义（基于 autodl.art ComfyUI API 页面）"""

RESOLUTION_ALL_4 = ["768p横", "768p竖", "480p横", "480p竖"]
RESOLUTION_5 = RESOLUTION_ALL_4 + ["1080p横"]
RESOLUTION_6_15S = RESOLUTION_ALL_4 + ["480p(1:1)", "768p(1:1)"]
RESOLUTION_9_V5 = RESOLUTION_5 + ["1080p竖", "1080p(1:1)", "480p(1:1)", "768p(1:1)"]
RESOLUTION_736 = ["736p横", "736p竖", "736p(1:1)"]

WORKFLOWS = [
    {
        "id": "minimax_h3_image_audio_to_video_v2_15s",
        "name": "H3 多图多音频生视频 15s",
        "short_name": "多图多音频15s",
        "desc": "MiniMax H3 多图多音频参考生视频，最长 15 秒。未做包装、门槛较高，需精确控制提示词。最多 9 图 + 3 音频。",
        "resolutions": RESOLUTION_ALL_4,
        "duration_max": 15,
        "has_seed": True,
        "has_prompt": True,
        "max_images": 9,
        "max_audios": 3,
        "ref_prefix": "ref_image_",
        "audio_prefix": "ref_audio_",
        "frame_mode": None,
    },
    {
        "id": "minimax_h3_lightx2v_v5_15s",
        "name": "H3 多图生视频 15s",
        "short_name": "多图生视频15s",
        "desc": "MiniMax H3 多图参考生成视频，最长 15 秒。最多 8 张参考图片。",
        "resolutions": RESOLUTION_6_15S,
        "duration_max": 15,
        "has_seed": True,
        "has_prompt": True,
        "max_images": 8,
        "max_audios": 0,
        "ref_prefix": "ref_image_",
        "audio_prefix": None,
        "frame_mode": None,
    },
    {
        "id": "minimax_h3_image_audio_to_video_v2",
        "name": "H3 多图多音频生视频",
        "short_name": "多图多音频",
        "desc": "MiniMax H3 多图多音频参考生视频。未做包装、门槛较高，需精确控制提示词。最多 8 图 + 3 音频。",
        "resolutions": RESOLUTION_5,
        "duration_max": 10,
        "has_seed": True,
        "has_prompt": True,
        "max_images": 8,
        "max_audios": 3,
        "ref_prefix": "ref_image_",
        "audio_prefix": "ref_audio_",
        "frame_mode": None,
    },
    {
        "id": "minimax_h3_image_audio_to_video",
        "name": "H3 图生视频-音频同步（自动对口型）",
        "short_name": "图音频对口型",
        "desc": "上传人物/角色图片及对应音频，生成与音频同步的动态视频（口型/表情/动作同步）。1 图 + 1 音频，无 prompt 字段，用 audio_duration。",
        "resolutions": RESOLUTION_5,
        "duration_max": 15,
        "has_seed": False,
        "has_prompt": False,
        "duration_field": "audio_duration",
        "max_images": 1,
        "max_audios": 1,
        "ref_prefix": "ref_image_",
        "audio_prefix": "ref_audio_",
        "frame_mode": None,
    },
    {
        "id": "minimax_h3_lightx2v_v5",
        "name": "H3 多图参考生视频",
        "short_name": "多图参考生视频",
        "desc": "MiniMax H3 多图参考生成视频。最多 9 张参考图片。",
        "resolutions": RESOLUTION_9_V5,
        "duration_max": 10,
        "has_seed": True,
        "has_prompt": True,
        "max_images": 9,
        "max_audios": 0,
        "ref_prefix": "ref_image_",
        "audio_prefix": None,
        "frame_mode": None,
    },
    {
        "id": "minimax_h3_lightx2v_no_pic",
        "name": "H3 文生视频",
        "short_name": "文生视频",
        "desc": "一句话生成 AI 视频，无参考图。支持多种分辨率及 1-15s 时长。",
        "resolutions": RESOLUTION_ALL_4,
        "duration_max": 15,
        "has_seed": False,
        "has_prompt": True,
        "max_images": 0,
        "max_audios": 0,
        "ref_prefix": None,
        "audio_prefix": None,
        "frame_mode": None,
    },
    {
        "id": "minimax_h3_lightx2v",
        "name": "H3 首尾帧生成视频（旧版）",
        "short_name": "首尾帧生视频旧版",
        "desc": "上传首帧与尾帧图片，提示词控制两帧之间的运动轨迹。duration + first_frame + last_frame（无 seed）。",
        "resolutions": RESOLUTION_ALL_4,
        "duration_max": 15,
        "has_seed": False,
        "has_prompt": True,
        "max_images": 0,
        "max_audios": 0,
        "ref_prefix": None,
        "audio_prefix": None,
        "frame_mode": "first_last",
    },
    # ---------- 新版 B99 系列 ----------
    {
        "id": "minimax_h3_b99_001",
        "name": "H3 文生视频 v2",
        "short_name": "文生视频v2",
        "desc": "一句话生成 AI 视频，新版本，支持 seed 复现/变异。分辨率可选 736p 系列。",
        "resolutions": RESOLUTION_736,
        "duration_max": 15,
        "has_seed": True,
        "has_prompt": True,
        "max_images": 0,
        "max_audios": 0,
        "ref_prefix": None,
        "audio_prefix": None,
        "frame_mode": None,
    },
    {
        "id": "minimax_h3_b99_002",
        "name": "H3 首尾帧 v2",
        "short_name": "首尾帧v2",
        "desc": "新版本首尾帧，支持 seed。首帧 last_frame 必须，分辨率 736p 系列。",
        "resolutions": RESOLUTION_736,
        "duration_max": 15,
        "has_seed": True,
        "has_prompt": True,
        "max_images": 0,
        "max_audios": 0,
        "ref_prefix": None,
        "audio_prefix": None,
        "frame_mode": "first_last",
    },
    {
        "id": "minimax_h3_b99_003_12s",
        "name": "H3 多图生视频 12s",
        "short_name": "多图生视频12s",
        "desc": "多图参考生成视频，最长 12 秒，最多 9 图，支持 seed。",
        "resolutions": RESOLUTION_736,
        "duration_max": 12,
        "has_seed": True,
        "has_prompt": True,
        "max_images": 9,
        "max_audios": 0,
        "ref_prefix": "ref_image_",
        "audio_prefix": None,
        "frame_mode": None,
    },
]

WORKFLOW_BY_ID = {w["id"]: w for w in WORKFLOWS}

SEED_MIN = 1
SEED_MAX = 999999999999999
